services:
  - type: web
    name: azvoiceclone
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: APP_HOST
        value: "0.0.0.0"
      - key: APP_PORT
        value: "10000"
    healthCheckPath: /